# Public endpoint for the school schedule.
server {
    listen 80;
    listen [::]:80;

    server_name rasp.gymn19.ru;

    access_log /data/logs/rasp.gymn19.ru_access.log standard;
    error_log  /data/logs/rasp.gymn19.ru_error.log warn;

    include conf.d/include/letsencrypt-acme-challenge.conf;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name rasp.gymn19.ru;

    ssl_certificate     /etc/letsencrypt/live/rasp.gymn19.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rasp.gymn19.ru/privkey.pem;
    include conf.d/include/ssl-cache.conf;
    include conf.d/include/ssl-ciphers.conf;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    access_log /data/logs/rasp.gymn19.ru_access.log standard;
    error_log  /data/logs/rasp.gymn19.ru_error.log warn;

    include conf.d/include/block-exploits.conf;

    location / {
        proxy_pass http://172.16.13.35:8085;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
